### ISSUE TITLE
java.lang.NullPointerException when running run-app

### ISSUE THREAD

**Issue by golden75** [elswob/Badger#5]
Hi I was following the workflow in the Bagder:
   When I got to the point to run-app: the following error came about: 
I am not sure hot to rectify this ? 

`grails prod run-app --stacktrace`

```
| Error Error occurred running Grails CLI: null (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.NullPointerException
	at org.grails.cli.GrailsCli.initializeProfile(GrailsCli.groovy:516)
	at org.grails.cli.GrailsCli.initializeApplication(GrailsCli.groovy:307)
	at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:270)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:159)
| Error Error occurred running Grails CLI: null
```

**Comment by elswob** [comment]
Hi, what version of Grails are you using? Also, have you tried any of these suggestions - http://stackoverflow.com/questions/29758697/error-occurred-running-grails-cli-null-when-running-grails-3-0-command-line ?

**Comment by golden75** [comment]
I was using Grails 3.2.9 and JDK 1.8. And I used the above suggestion but, it did not work for me. Said some thing on the line as the JDK 1.8 has removed the support for handling CLI.

So I removed my current version and started with a new version of Grails (Grails version: 2.3.7) and JDK 1.6 

Question: I am following the Badger installation guide: and in [Configure](https://github.com/elswob/Badger#configure) section:
I think I am little lost. So when creating the DB, using the below
 `su postgres
createdb Badger -O 'your_user_name' -E UTF8 --locale=en_GB.utf8 -T template0;`
 
From where should I be creating the db? (location)
should I be inside the Badger directory /usr/local/Projects/Badger ?
Or should I be inside the pgsql directory ? (/usr/local/pgsql ) ?

**Comment by elswob** [comment]
You can run that command from anywhere, it just creates a postgres database. 

As Badger is now a little old, and not really being maintained, it may well be problematic. Instead, you might want to try GenomeHubs - https://genomehubs.gitbooks.io/genomehubs/content/ which I believe is very easy to set up.

**Comment by golden75** [comment]
Thanks for the reply and the alternative. But I need to set it up using the Badger. As this web server was using badger and it has been included in the publication.
